version: "3"

services:
  rocket:
    build:
      context: .
      dockerfile: ./rocket/Dockerfile
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf