version: "2"

services:
  rocket:
    build:
      context: ./rocket
      dockerfile: ./Dockerfile
  nginx:
    image: nginx
    ports:
      - 22000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf